#!/usr/bin/env node

// @flow

const cli = require('commander');
const asyncUtils = require('./../dist/lib/async.js');
const alignFlowVersions = require('./../dist/commands/align-versions.js');

cli.parse(process.argv);

asyncUtils.exec(alignFlowVersions);
