#!/usr/bin/env node

// @flow

const cli = require('commander');
const asyncUtils = require('./../dist/lib/async.js');
const installFlowTypes = require('./../dist/commands/install-types.js');

cli.allowUnknownOption(true).parse(process.argv);

asyncUtils.exec(installFlowTypes);
