#!/usr/bin/env node

// @flow

const cli = require('commander');
const asyncUtils = require('./../dist/lib/async.js');
const createDependencyFlowTypeStubs = require('./../dist/commands/create-stubs.js');

cli
  .option('-u, --use-root', 'If passed the stubs will be created in the root of the mono-repository.', false)
  .parse(process.argv);

asyncUtils.exec(createDependencyFlowTypeStubs, {
  useRoot: cli.useRoot
});
