#!/usr/bin/env node

// @flow

const cli = require('commander');
const asyncUtils = require('./../dist/lib/async.js');
const createDependencyFlowTypeStubs = require('./../dist/commands/create-stubs.js');

cli.parse(process.argv);

asyncUtils.exec(createDependencyFlowTypeStubs, ...cli.args);
